name: 14 - Working with Artifacts

on:
  workflow_dispatch:

jobs:
  test-build:
    name: Pre Flow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app

    steps:
      - name: Checkouts
        uses: actions/checkout@v3

      - name: Cache npm
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm dependencies
        run: npm install

      - name: test
        run: npm run test -- --coverage

      - name: Build
        run: npm run build


      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: react-app/build
    
  deploy:
    runs-on: ubuntu-latest
    needs: test-build

    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build